version: "3"
services:
  redis:
    restart: always
    image: redis
    volumes:
      - "${PWD}/.env:/opt/tellform/.env"
  mongo:
    restart: always
    image: mongo
    volumes: 
      - "$ROOT/mongo:/data"
  tellform:
    image: tellform/app:stable
    env_file:
      - .env
    volumes:
      - "${PWD}/.env:/opt/tellform/.env"
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
  web:
    image: tellform/nginx:stable
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "20523:20523"
    env_file:
      - .env
    volumes: 
      - "$ROOT/certs:/certs"
